### ISSUE TITLE
Setting colorscheme triggers errors

### ISSUE THREAD

**Issue by lynxcs** [bagrat/vim-buffet#11]
Whenever I try to set the colorscheme inside of vim (It works fine if done inside of vimrc) , it throws out these errors (which I've traced back to vim-workspace).

![2017-12-17-143801_1920x1080_scrot](https://user-images.githubusercontent.com/9138137/34078655-438155e2-e327-11e7-8d49-8c9847dc5a62.png)

**Comment by bagrat** [comment]
thanks for reporting this @lynxcs.

**Comment by aruntk** [comment]
@bagrat any updates on this issue?

**Comment by bagrat** [comment]
@aruntk sorry for the delay, I will make sure to take care of this during the weekend.

**Comment by dmitriyK1** [comment]
I also have this issue(

**Comment by bagrat** [comment]
Hey everyone!

Sorry for a long silence here.

I am doing a major rewrite (see `rewrite` branch), and have already addressed this issue. Please hang tight and I will push everything very soon.

**Comment by bagrat** [comment]
The rewrite branch is not in the master! This issues is fixed.
