### ISSUE TITLE
Error detected while processing function buffetrenderer[1]

### ISSUE THREAD

**Issue by Newexplorer** [bagrat/vim-buffet#15]
When starting Vim I get this message:
```
Error detected while processing function buffetrenderer[1] .. buffet#update:
E684: last index out of range[0]
```
The error disappears after commenting out the plugin in my vimrc file.
I'm using:
VIM - Vi IMproved 7.4
Included patches: 1-1689

**Comment by bagrat** [comment]
Thanks for creating the issue @Newexplorer.

I have just built the exact version you posted and not able to reproduce. Are you starting vim with any argument?

Also, could you please the list of other plugins you are using?

**Comment by Newexplorer** [comment]
I don't run vim with any arguments.
The full list:
```
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-abolish'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-fugitive'
Plugin 'easymotion/vim-easymotion'
Plugin 'scrooloose/nerdtree'
Plugin 'tomtom/tlib_vim'
Plugin 'honza/vim-snippets'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'SirVer/ultisnips'
Plugin 'jeffkreeftmeijer/vim-numbertoggle'
Plugin 'scrooloose/syntastic'
Plugin 'vim-scripts/SearchComplete'
Plugin 'soulston/vim-listtrans'
Plugin 'xolox/vim-notes'
Plugin 'xolox/vim-misc'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'Lokaltog/vim-powerline'
Plugin 'nixon/vim-vmath'
Plugin 'tpope/vim-unimpaired'
Plugin 'godlygeek/tabular'
Plugin 'qpkorr/vim-renamer'
Plugin 'vim-latex/vim-latex'
Plugin 'vim-scripts/perl-support.vim'
Plugin 'mhinz/vim-startify'
Plugin 'junegunn/vim-easy-align'
Plugin 'dhruvasagar/vim-table-mode'
" Plugin 'bagrat/vim-buffet'
Plugin 'vim-scripts/marvim'
Plugin 'vim-scripts/ReplaceWithRegister'
Plugin 'tmhedberg/matchit'
Plugin 'bronson/vim-trailing-whitespace'
Plugin 'vimwiki/vimwiki'
Plugin 'KabbAmine/lazyList.vim'
Plugin 'jlanzarotta/bufexplorer'
Plugin 'junegunn/goyo.vim'
Plugin 'vim-utils/vim-man'
Plugin 'tpope/vim-commentary'
Plugin 'xuhdev/vim-latex-live-preview'
Plugin 'bronson/vim-visual-star-search'
Plugin 'mbbill/undotree'
Plugin 'junegunn/fzf'
Plugin 'rhysd/clever-f.vim'
Plugin 'mileszs/ack.vim'
Plugin 'osyo-manga/vim-over'

```

**Comment by Newexplorer** [comment]
I experimented a bit. I commented all the plugins except for vim-buffet. It worked.
Because I had seen a post about vim-startify before, I commented out only the vim-startify plugin in my vimrc.
Result was that everything worked, including vim-buffet. Apparently, vim-buffet and vim-startify cannot work well alongside each other.

**Comment by Newexplorer** [comment]
I commented all the vim plugins except for vim-buffet and it worked.
Because I had seen a post about the plugin vim-startify, I commented out only this plugin in my vimrc. Everything worked including vim-buffet.
The plugin vim-startify and vim-buffet doesn't seem to be working well together. 
More information: I have Python 2.7.12 on my system.
If you need more information, let me know.

**Comment by bagrat** [comment]
@Newexplorer thanks for tracing it down, I was able to reproduce it. Will be working on fixing it.

**Comment by bagrat** [comment]
@Newexplorer 843d9d15e5bda15a2807526ba00cbd44039e5d83 should fix this, please update the plugin and see if it works.

**Comment by bagrat** [comment]
The problem was that `vim-startify` creates a new **unlisted buffer** at the startup, thus removing the initial empty **listed** one. `vim-buffet` was relying on the fact that there is always at least one listed buffer in the buffer list.

**Comment by Newexplorer** [comment]
Update worked. Thank you.
