### ISSUE TITLE
Customize top left icon

### ISSUE THREAD

**Issue by bitshiftnetau** [bagrat/vim-buffet#17]
Hey, 

Not sure if this is part of the plugin or just native to vim, but I would love a way to customize the icon in the top left-hand corner i.e. the blue thing with 9 black dots. 

Thanks!

![vim](https://user-images.githubusercontent.com/26871600/54494044-436a3a00-492a-11e9-964b-18d41c583a10.png)

**Comment by bitshiftnetau** [comment]
Nevermind, found it.

**Comment by bitshiftnetau** [comment]
Nevermind, found it

**Comment by bagrat** [comment]
I'm glad you found it @bitshiftnetau. Gonna answer regardless for future.

That blue thing is actually a Tabpage representation. As many Tabpages you will have in vim, that many blue things will be there, with buffers following the active one. So for example, if you have 5 Tabpages, and currently have 3rd Tabpage open, then you will have:

```
| # | # | # | ... buffers ... | # | # |
```

To change the icon of it, there is a dedicated variable for that, called `g:buffet_tab_icon`, just assign it in your vimrc like this (e.g. you want the icon to be `$`):

```
let g:buffet_tab_icon = "$"
```
