### ISSUE TITLE
vim-buffet doesn't work on neovim

### ISSUE THREAD

**Issue by mnrce** [bagrat/vim-buffet#20]
Hi,

I just installed vim-buffet in neovim using vim-plug, after restarting neovim, the tabline appear, but it only showed with the active buffer only, not any other buffers.

I tested in vim 8.1 and it showed fine.

I'm using neovim 0.3.5.

Please tell me if I need to provide any more information, thanks.

**Comment by bagrat** [comment]
@mnrce thanks for creating this issue and providing all the info. I'll be able to have a look into this in a week and will keep updating this issue.

**Comment by bagrat** [comment]
@mnrce I have just tested with neovim v0.3.7 and it works fine. Can you please try upgrading neovim and see if the issue continues to appear?

**Comment by mnrce** [comment]
I've just tested with neovim v0.3.7 and v0.4.0-1119-g8c7e41f59 and still had the same issue:

![image](https://user-images.githubusercontent.com/13317164/60180990-6a021000-984b-11e9-96a3-02b49bc05bc8.png)
You can see that `:ls` show two buffers but the tabline only show one.

**Comment by bagrat** [comment]
Thanks for posting the screenshot @mnrce. I think the problem is with another plugin. Are you using `airline` for statusline?

**Comment by mnrce** [comment]
> Thanks for posting the screenshot @mnrce. I think the problem is with another plugin. Are you using `airline` for statusline?

I'm using lightline for statusline.

**Comment by bagrat** [comment]
@mnrce figured it out. So you probably have the Lightline Tabline enabled by default. The reason you see just one buffer, is that the Lightline Tabline actually shows the tabs and not buffers, and the tab just shows the current active buffer. All you need to do is just disable the Lightline Tabline, should be something like this:

```
let g:lightline.enable.tabline = 0
```

Please confirm that it worked for you, or let me know otherwise and let's continue investigating.

**Comment by mnrce** [comment]
> @mnrce figured it out. So you probably have the Lightline Tabline enabled by default. The reason you see just one buffer, is that the Lightline Tabline actually shows the tabs and not buffers, and the tab just shows the current active buffer. All you need to do is just disable the Lightline Tabline, should be something like this:
> 
> ```
> let g:lightline.enable.tabline = 0
> ```
> 
> Please confirm that it worked for you, or let me know otherwise and let's continue investigating.

It works now, thank you. I didn't know lightline has tabline, and for some reason it worked in vim but not neovim, so I didn't think lightline was the reason.

**Comment by bagrat** [comment]
I am glad it worked for you @mnrce!

@EdgarOrtegaRamirez @nifoc could you please check if this works for you as well?

**Comment by EdgarOrtegaRamirez** [comment]
In my case this was the setting:

```vim
let g:lightline = {
      \ 'enable': {
      \   'tabline': 0
      \ },
      \ }
```

and this is how it looks 
![image](https://user-images.githubusercontent.com/2790520/60219879-d4aa5000-9839-11e9-9cde-b5f30bcac304.png)

**Comment by bagrat** [comment]
@EdgarOrtegaRamirez great, that's what it is supposed to look like. You can customize the colors the way you want as well as apply for fancy stuff like [this](https://github.com/bagrat/vim-buffet#how-do-i-get-the-look-like-in-the-screenshot). Note, the blue `#`-es are the Tabpages. So in your case you have 4 Tabpages, and currently Tabpage #3 is active.

**Comment by hrai** [comment]
> In my case this was the setting:
> 
> ```viml
> let g:lightline = {
>       \ 'enable': {
>       \   'tabline': 0
>       \ },
>       \ }
> ```
> 
> and this is how it looks without any additional buffet config set
> ![image](https://user-images.githubusercontent.com/2790520/60219879-d4aa5000-9839-11e9-9cde-b5f30bcac304.png)

This is what worked for me. Perhaps we can leave this issue open as it's not as obvious to find.

**Comment by baIIoon** [comment]
@hrai, should I add this to README?

**Comment by baIIoon** [comment]
@hrai, https://github.com/bagrat/vim-buffet#faq

**Comment by hrai** [comment]
@baIIoon not sure why that didn't work for me.

**Comment by baIIoon** [comment]
@hrai, I updated the README, https://github.com/bagrat/vim-buffet/commit/27d5a452b214461ec78d0f5fc7704dc3ed6becc3. I don't have much experience with VimL to answer (clarify) that, so sorry!
