### ISSUE TITLE
Disambiguate buffer name

### ISSUE THREAD

**Issue by chunkhang** [bagrat/vim-buffet#25]
Right now, we're only taking the basename of the file. We can take a look at how **vim-buftabline** managed to disambiguate files with the same basename [here](https://github.com/ap/vim-buftabline/blob/14d208b1fa5f4308383e3ce429d57c84423029f9/plugin/buftabline.vim#L87).

So, ideally, we get something like this:
```
# | apple/index.txt | banana/index.txt |
```

**Comment by bagrat** [comment]
This is a great idea and something I had in mind but never had time to work on. Thanks for creating this one and linking *vim-buftabline * example 👍
