### ISSUE TITLE
Quickfix buffer should not be shown

### ISSUE THREAD

**Issue by chunkhang** [bagrat/vim-buffet#26]
By right, we need to make sure that the quickfix buffer doesn't appear in the tabline at all.

**Comment by bagrat** [comment]
Some plugins actually open the QF buffer as a hidden one, but looks like not all of them.

**Comment by chunkhang** [comment]
Ah, I usually launch Vim with something like `vim -q <(rg --vimgrep something)` to get the quickfix list populated. So, it's not hidden.
