### ISSUE TITLE
how to change color

### ISSUE THREAD

**Issue by yanke1311** [bagrat/vim-buffet#37]
while I defined a function with name g:BuffetSetCustomColors, I don't know how to use it. if the plug will call the function automatically， or  should I call it manually? 
I try to call it before/after the plug been loaded, but it don't work

**Comment by ztoiax** [comment]
### my settings
`function! g:BuffetSetCustomColors()
    hi! BuffetCurrentBuffer cterm=NONE ctermbg=106 ctermfg=8 guibg=#b8bb26 guifg=#000000
    hi! BuffetTrunc cterm=bold ctermbg=66 ctermfg=8 guibg=#458588 guifg=#000000
    hi! BuffetBuffer cterm=NONE ctermbg=239 ctermfg=8 guibg=#504945 guifg=#000000
    hi! BuffetTab cterm=NONE ctermbg=66 ctermfg=8 guibg=#458588 guifg=#000000
    hi! BuffetActiveBuffer cterm=NONE ctermbg=10 ctermfg=239 guibg=#999999 guifg=#504945
endfunction
`

**Comment by ztoiax** [comment]
### my settings
function! g:BuffetSetCustomColors()
hi! BuffetCurrentBuffer cterm=NONE ctermbg=106 ctermfg=8 guibg=#b8bb26 guifg=#000000
hi! BuffetTrunc cterm=bold ctermbg=66 ctermfg=8 guibg=#458588 guifg=#000000
hi! BuffetBuffer cterm=NONE ctermbg=239 ctermfg=8 guibg=#504945 guifg=#000000
hi! BuffetTab cterm=NONE ctermbg=66 ctermfg=8 guibg=#458588 guifg=#000000
hi! BuffetActiveBuffer cterm=NONE ctermbg=10 ctermfg=239 guibg=#999999 guifg=#504945
endfunction

**Comment by bagrat** [comment]
Sorry for late response @yanke1311, the function is [being called automatically](https://github.com/bagrat/vim-buffet/blob/b17850f3a8f3084471d4ed4a201f8a5ec0abd857/plugin/buffet.vim#L173-L175) by the plugin, you just need to make sure your function is defined before the plugin is loaded. Can you please show your config?

**Comment by yanke1311** [comment]
thank you!
