### ISSUE TITLE
Separators not correctly displayed when termguicolors is set

### ISSUE THREAD

**Issue by ChrisAmelia** [bagrat/vim-buffet#38]
Using following config:

```vim
set nocompatible
set runtimepath^=~/.local/share/nvim/plugged/vim-buffet
filetype plugin indent on
syntax on
set hidden

set termguicolors

let g:buffet_powerline_separators = 1
```

This is the result when `termguicolors` is not set:

![image](https://user-images.githubusercontent.com/16366403/69500149-d8c9bf00-0ef8-11ea-8967-4d87427370a2.png)

And this is the result when `termguicolors` is set:

![image](https://user-images.githubusercontent.com/16366403/69500164-f4cd6080-0ef8-11ea-96e0-9975ce1ccbdd.png)

**To reproduce**:

Comment/uncomment `set termguicolors` and type:

```sh
nvim -u init.vim thing thing2
```

**Comment by Th3Whit3Wolf** [comment]
Is there any work around for this?

**Comment by ChrisAmelia** [comment]
Rewriting  the highlights should do it, especially in https://github.com/bagrat/vim-buffet/blob/master/plugin/buffet.vim#L160

Replace:

```vim
hi! BuffetBuffer cterm=NONE ctermbg=10 ctermfg=8 guibg=#999999 guifg=#000000
```

with:

```vim
hi! BuffetBuffer ctermbg=none guibg=none guifg=none
```

Give a look at: https://github.com/bagrat/vim-buffet/compare/master...ChrisAmelia:master

**Comment by Th3Whit3Wolf** [comment]
@ChrisAmelia I tried install yours and I get

```sh
Error detected while processing function buffet#render[2]..<SNR>68_Render:
line   78:
E121: Undefined variable: g:leftCircle
Press ENTER or type command to continue
```

**Comment by ChrisAmelia** [comment]
Define in your init.vim:

```vim
let g:rightCircle = "\ue0b4"
let g:leftCircle  = "\ue0b6"
```

**Comment by Th3Whit3Wolf** [comment]
From what I can tell the issue comes from checking if the user is using a gui and then deciding off that to use guicolors. The problem is that obviously some terminals support the same kind of colors as guis. My pull request fixes this by checking if the user is in a gui or has set termguicolors.

**Comment by bagrat** [comment]
This is fixed thanks to @Th3Whit3Wolf
