### ISSUE TITLE
Not clear that vim devicons needs to be loaded before vim-buffet

### ISSUE THREAD

**Issue by Akin909** [bagrat/vim-buffet#42]
Firstly thanks for the great plugin :100: it's been super useful.
When I initially installed it I tried to get it working with vim devicons but kept finding that the icons wouldn't show. I re-read the instructions in the `README` and realised (although it isn't explicitly stated) that I had to load vim devicons _before_ vim buffet
```vim
Plug 'vim-devicons' "<-- once move here it works fine
Plug 'vim-buffet'
Plug 'vim-devicons' "<-- Initially below buffet, doesn't load icons
```

This is probably not too big a deal but I think it would be clearer if the `README.md` was explicit about this _or_ maybe the plugin could do something similar to `lightline-bufferline` which seems to be able to load the devicons regardless of the positioning.

**Comment by bagrat** [comment]
@Akin909 thanks for pointing this out! I have [updated the README](https://github.com/bagrat/vim-buffet/pull/46) to address that.
