### ISSUE TITLE
Colors inherit from current theme?

### ISSUE THREAD

**Issue by macintacos** [bagrat/vim-buffet#49]
For example, I use Dracula, and was surprised that this plugin did not inherit the colors from that theme instead of using a default. Needing to manually change them isn't impossible, but it is a little annoying.

Unless I'm missing something and have my configuration messed up somehow?

**Comment by baIIoon** [comment]
Can you provide a screenshot? I prefer you to config the Highlights manually because the plugin is kind of hard for newcomers to adding new features. So instead of refactoring it, I'm trying to rewrite it using Lua (branch `lua`?) and maybe I will add Highlights based on the color scheme.

**Comment by macintacos** [comment]
I decided to bite the bullet and just edit the color scheme to match Dracula's colors directly (did that before I saw your update 🙂). This is what I came up with (which works great for me):

```vim
function! g:BuffetSetCustomColors()
  hi! BuffetCurrentBuffer    gui=NONE guibg=#50fa7b guifg=#282a36
  hi! BuffetActiveBuffer     gui=NONE guibg=#bd93f9 guifg=#282a36
  hi! BuffetBuffer           gui=NONE guibg=#282a36 guifg=#6272a4
  hi! BuffetModCurrentBuffer gui=NONE guibg=#8be9fd guifg=#282a36
  hi! BuffetModActiveBuffer  gui=NONE guibg=#ffb86c guifg=#282a36
  hi! BuffetModBuffer        gui=NONE guibg=#ff5555 guifg=#282a36
  hi! BuffetTrunc            gui=NONE guibg=#bd93f9 guifg=#282a36
  hi! BuffetTab              gui=NONE guibg=#bd93f9 guifg=#282a36
endfunction
```
