### ISSUE TITLE
I can't change the color of the buffers

### ISSUE THREAD

**Issue by Cris-lml007** [bagrat/vim-buffet#61]
I cannot change the color of the buffers, and I have already tried several things to change it but nothing that I achieve, only when I put the function that is in the plugin documentation the active buffer turns purple, I tried to change the values ​​of the Colors but does not affect anything, please help.

**Comment by alexzanderr** [comment]
same here!

![image](https://user-images.githubusercontent.com/54772464/122434366-b3e7e180-cf9f-11eb-9f18-58a2436d0db9.png)

in my .vimrc:
```
function! g:BuffetSetCustomColors()
  hi! BuffetCurrentBuffer ctermbg=235 ctermfg=193
  hi! BuffetActiveBuffer ctermbg=235 ctermfg=193
  hi! BuffetTab ctermbg=235 ctermfg=193
endfunction
```
and these colors are definitely not like those in the photo.

and ofc, function is loaded before the plugin.

**Comment by Cris-lml007** [comment]
After doing several tests I came to the conclusion that it is due to the terminal format or in other words, that those colors do not influence the terminals but rather the graphic mode of vim or also called gvim.

**Comment by qaqcxh** [comment]
There exists some bugs in this plugin when handling terminal vim, see #63

**Comment by Cris-lml007** [comment]
I just fixed the error in the colors, it should be added to the .vimrc :   
`set termguicolors`
